services:
  backend:
    build: ./backend
    container_name: revdojo-backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/revdojo
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      APP_JWT_SECRET: supersecretjwtkey
    networks:
      - revdojo-net

  # frontend:
  #   build: ./frontend
  #   container_name: revdojo-frontend
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - backend
  #   environment:
  #     REACT_APP_API_URL: http://localhost:8080/api
  #   networks:
  #     - revdojo-net

  db:
    image: postgres:latest
    container_name: revdojo-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: revdojo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - revdojo-net

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: revdojo-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - revdojo-net

volumes:
  postgres_data:

networks:
  revdojo-net:
    driver: bridge
