#Database
POSTGRESQL_USER: devuser
POSTGRESQL_PASSWORD: devpassword
POSTGRESQL_DB: devdb
POSTGRESQL_HOST: 172.18.0.2
POSTGRESQL_PORT: 5432

#Server
CONTAINER_PORT: 8085
ACTIVE_PROFILE: dev

#Email Config
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID: dracolord786@gmail.com
EMAIL_PASSWORD: ${EMAIL_PASSWORD}
VERIFY_EMAIL_HOST: http://localhost:8085

JWT_EXPIRATION: 432_000_000
JWT_SECRET: ${SECRET}
